build:
    environment:
        php:
            version: 5.5.9
    tests:
        override:
           -
              command: './tools/run-tests.sh'
              coverage:
                  file: 'tools/coverage.xml'
                  format: 'php-clover'
